import { Job, Task, Company, Opportunity, ScraperRun, AutomationBreakdown, AIBlueprint } from './types';

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    company: 'TechCorp',
    title: 'Customer Support Specialist',
    location: 'San Francisco, CA',
    remoteType: 'hybrid',
    salaryMin: 55000,
    salaryMax: 75000,
    salaryCurrency: 'USD',
    automationPercentage: 78,
    opportunityScore: 92,
    estimatedSavings: 48000,
    description: 'Handle customer inquiries, troubleshoot issues, and provide product support.',
    responsibilities: [
      'Respond to customer inquiries via email, chat, and phone',
      'Troubleshoot technical issues and provide solutions',
      'Document customer interactions in CRM system',
      'Escalate complex issues to senior support team',
      'Create and maintain support documentation',
    ],
    requirements: [
      '2+ years of customer support experience',
      'Excellent written and verbal communication',
      'Experience with CRM systems',
      'Problem-solving mindset',
      'Ability to work in fast-paced environment',
    ],
    tools: ['Zendesk', 'Slack', 'Jira', 'Google Suite'],
    skills: ['Customer Service', 'Technical Troubleshooting', 'Documentation', 'CRM'],
    lastUpdated: '2024-03-20',
    status: 'active',
    sourceUrl: 'https://example.com/job/1',
  },
  {
    id: 'job-2',
    company: 'SalesFlow Inc',
    title: 'Sales Development Representative',
    location: 'New York, NY',
    remoteType: 'remote',
    salaryMin: 60000,
    salaryMax: 80000,
    salaryCurrency: 'USD',
    automationPercentage: 65,
    opportunityScore: 85,
    estimatedSavings: 42000,
    description: 'Generate and qualify leads for the sales team through outbound prospecting.',
    responsibilities: [
      'Conduct outbound prospecting via phone, email, and LinkedIn',
      'Qualify inbound leads and schedule demos',
      'Research potential customers and industries',
      'Update CRM with lead information and activities',
      'Meet monthly quotas for qualified meetings',
    ],
    requirements: [
      '1-2 years of SDR or sales experience',
      'Strong communication and persuasion skills',
      'Experience with Salesforce or similar CRM',
      'Self-motivated and goal-oriented',
      'Bachelor degree preferred',
    ],
    tools: ['Salesforce', 'Outreach', 'LinkedIn Sales Navigator', 'ZoomInfo'],
    skills: ['Lead Generation', 'Cold Calling', 'Email Outreach', 'CRM Management'],
    lastUpdated: '2024-03-21',
    status: 'active',
    sourceUrl: 'https://example.com/job/2',
  },
  {
    id: 'job-3',
    company: 'DataWorks',
    title: 'Operations Analyst',
    location: 'Austin, TX',
    remoteType: 'hybrid',
    salaryMin: 70000,
    salaryMax: 90000,
    salaryCurrency: 'USD',
    automationPercentage: 82,
    opportunityScore: 88,
    estimatedSavings: 56000,
    description: 'Analyze operational processes and implement data-driven improvements.',
    responsibilities: [
      'Analyze operational data and identify inefficiencies',
      'Create reports and dashboards for stakeholders',
      'Document and optimize business processes',
      'Coordinate with cross-functional teams on projects',
      'Maintain data quality and integrity',
    ],
    requirements: [
      '2-3 years of operations or analyst experience',
      'Strong Excel and SQL skills',
      'Experience with data visualization tools',
      'Analytical mindset and attention to detail',
      'Project management capabilities',
    ],
    tools: ['Excel', 'SQL', 'Tableau', 'Asana', 'Google Analytics'],
    skills: ['Data Analysis', 'Process Optimization', 'Reporting', 'SQL'],
    lastUpdated: '2024-03-19',
    status: 'active',
    sourceUrl: 'https://example.com/job/3',
  },
  {
    id: 'job-4',
    company: 'MediaHub',
    title: 'Content Moderator',
    location: 'Remote',
    remoteType: 'remote',
    salaryMin: 45000,
    salaryMax: 60000,
    salaryCurrency: 'USD',
    automationPercentage: 85,
    opportunityScore: 90,
    estimatedSavings: 38000,
    description: 'Review and moderate user-generated content for policy compliance.',
    responsibilities: [
      'Review flagged content for policy violations',
      'Apply moderation guidelines consistently',
      'Escalate complex cases to senior moderators',
      'Document decisions and feedback',
      'Participate in policy calibration sessions',
    ],
    requirements: [
      '1+ years of content moderation experience',
      'Strong judgment and decision-making skills',
      'Ability to handle sensitive content',
      'Detail-oriented and consistent',
      'Fast typing and navigation skills',
    ],
    tools: ['Internal Moderation Platform', 'Slack', 'Jira'],
    skills: ['Content Moderation', 'Policy Enforcement', 'Decision Making'],
    lastUpdated: '2024-03-22',
    status: 'active',
    sourceUrl: 'https://example.com/job/4',
  },
  {
    id: 'job-5',
    company: 'FinanceFirst',
    title: 'Account Reconciliation Specialist',
    location: 'Chicago, IL',
    remoteType: 'onsite',
    salaryMin: 55000,
    salaryMax: 70000,
    salaryCurrency: 'USD',
    automationPercentage: 88,
    opportunityScore: 94,
    estimatedSavings: 52000,
    description: 'Perform account reconciliation and ensure financial accuracy.',
    responsibilities: [
      'Reconcile bank statements and general ledger accounts',
      'Investigate and resolve discrepancies',
      'Prepare reconciliation reports',
      'Maintain accurate financial records',
      'Support month-end close processes',
    ],
    requirements: [
      '2+ years of accounting or reconciliation experience',
      'Strong attention to detail',
      'Proficiency in Excel and accounting software',
      'Understanding of accounting principles',
      'Bachelor degree in Accounting or Finance',
    ],
    tools: ['QuickBooks', 'Excel', 'SAP', 'NetSuite'],
    skills: ['Account Reconciliation', 'Financial Analysis', 'Excel', 'Accounting'],
    lastUpdated: '2024-03-18',
    status: 'active',
    sourceUrl: 'https://example.com/job/5',
  },
  {
    id: 'job-6',
    company: 'HealthTech Solutions',
    title: 'Medical Billing Specialist',
    location: 'Boston, MA',
    remoteType: 'hybrid',
    salaryMin: 50000,
    salaryMax: 65000,
    salaryCurrency: 'USD',
    automationPercentage: 72,
    opportunityScore: 81,
    estimatedSavings: 41000,
    description: 'Process medical claims and ensure accurate billing.',
    responsibilities: [
      'Submit and follow up on insurance claims',
      'Review and correct claim denials',
      'Verify patient insurance coverage',
      'Maintain patient billing records',
      'Communicate with insurance companies',
    ],
    requirements: [
      '2+ years of medical billing experience',
      'Knowledge of ICD-10 and CPT codes',
      'Certified Professional Biller (CPB) preferred',
      'Strong attention to detail',
      'Experience with billing software',
    ],
    tools: ['Epic', 'Kareo', 'Athenahealth', 'Excel'],
    skills: ['Medical Billing', 'Insurance Claims', 'ICD-10', 'Claims Processing'],
    lastUpdated: '2024-03-21',
    status: 'active',
    sourceUrl: 'https://example.com/job/6',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1-1',
    jobId: 'job-1',
    name: 'Respond to routine customer inquiries',
    category: 'communication',
    judgmentLevel: 'low',
    interactionLevel: 'medium',
    automationPercentage: 95,
    description: 'Answer common questions about product features, pricing, and account management',
    complexity: 2,
  },
  {
    id: 'task-1-2',
    jobId: 'job-1',
    name: 'Troubleshoot technical issues',
    category: 'technical',
    judgmentLevel: 'medium',
    interactionLevel: 'medium',
    automationPercentage: 70,
    description: 'Diagnose and resolve technical problems with product usage',
    complexity: 5,
  },
  {
    id: 'task-1-3',
    jobId: 'job-1',
    name: 'Document customer interactions',
    category: 'documentation',
    judgmentLevel: 'low',
    interactionLevel: 'low',
    automationPercentage: 98,
    description: 'Log customer issues, resolutions, and feedback in CRM',
    complexity: 1,
  },
  {
    id: 'task-1-4',
    jobId: 'job-1',
    name: 'Escalate complex issues',
    category: 'coordination',
    judgmentLevel: 'high',
    interactionLevel: 'high',
    automationPercentage: 30,
    description: 'Identify and escalate issues requiring senior support',
    complexity: 7,
  },
  {
    id: 'task-1-5',
    jobId: 'job-1',
    name: 'Create support documentation',
    category: 'documentation',
    judgmentLevel: 'medium',
    interactionLevel: 'low',
    automationPercentage: 85,
    description: 'Write help articles and FAQs based on common issues',
    complexity: 4,
  },
  {
    id: 'task-2-1',
    jobId: 'job-2',
    name: 'Research potential customers',
    category: 'research',
    judgmentLevel: 'low',
    interactionLevel: 'low',
    automationPercentage: 92,
    description: 'Find and gather information about target companies and contacts',
    complexity: 2,
  },
  {
    id: 'task-2-2',
    jobId: 'job-2',
    name: 'Draft outbound emails',
    category: 'communication',
    judgmentLevel: 'low',
    interactionLevel: 'low',
    automationPercentage: 88,
    description: 'Create personalized outreach emails for prospects',
    complexity: 3,
  },
  {
    id: 'task-2-3',
    jobId: 'job-2',
    name: 'Qualify inbound leads',
    category: 'communication',
    judgmentLevel: 'medium',
    interactionLevel: 'high',
    automationPercentage: 60,
    description: 'Assess lead fit and readiness through discovery questions',
    complexity: 6,
  },
  {
    id: 'task-2-4',
    jobId: 'job-2',
    name: 'Update CRM records',
    category: 'documentation',
    judgmentLevel: 'low',
    interactionLevel: 'low',
    automationPercentage: 95,
    description: 'Log activities, notes, and lead status in Salesforce',
    complexity: 1,
  },
  {
    id: 'task-2-5',
    jobId: 'job-2',
    name: 'Schedule meetings',
    category: 'coordination',
    judgmentLevel: 'low',
    interactionLevel: 'medium',
    automationPercentage: 90,
    description: 'Coordinate calendars and book demos with qualified leads',
    complexity: 2,
  },
];

export const mockCompanies: Company[] = [
  {
    id: 'company-1',
    name: 'TechCorp',
    industry: 'Technology',
    size: '500-1000',
    totalJobs: 12,
    avgAutomation: 74,
    totalSavings: 520000,
  },
  {
    id: 'company-2',
    name: 'SalesFlow Inc',
    industry: 'SaaS',
    size: '100-500',
    totalJobs: 8,
    avgAutomation: 68,
    totalSavings: 340000,
  },
  {
    id: 'company-3',
    name: 'DataWorks',
    industry: 'Data Analytics',
    size: '500-1000',
    totalJobs: 15,
    avgAutomation: 79,
    totalSavings: 680000,
  },
  {
    id: 'company-4',
    name: 'MediaHub',
    industry: 'Media',
    size: '1000+',
    totalJobs: 24,
    avgAutomation: 82,
    totalSavings: 1200000,
  },
  {
    id: 'company-5',
    name: 'FinanceFirst',
    industry: 'Finance',
    size: '100-500',
    totalJobs: 6,
    avgAutomation: 85,
    totalSavings: 380000,
  },
];

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    company: 'MediaHub',
    role: 'Content Moderator',
    totalRoles: 8,
    avgSalary: 52500,
    automationPercentage: 85,
    estimatedSavings: 304000,
    status: 'new',
  },
  {
    id: 'opp-2',
    company: 'FinanceFirst',
    role: 'Account Reconciliation Specialist',
    totalRoles: 5,
    avgSalary: 62500,
    automationPercentage: 88,
    estimatedSavings: 275000,
    status: 'contacted',
  },
  {
    id: 'opp-3',
    company: 'TechCorp',
    role: 'Customer Support Specialist',
    totalRoles: 12,
    avgSalary: 65000,
    automationPercentage: 78,
    estimatedSavings: 576000,
    status: 'in-progress',
  },
  {
    id: 'opp-4',
    company: 'DataWorks',
    role: 'Operations Analyst',
    totalRoles: 7,
    avgSalary: 80000,
    automationPercentage: 82,
    estimatedSavings: 392000,
    status: 'new',
  },
];

export const mockScraperRuns: ScraperRun[] = [
  {
    id: 'run-1',
    source: 'LinkedIn Jobs API',
    status: 'success',
    jobsScraped: 1247,
    successRate: 98.5,
    errors: 19,
    timestamp: '2024-03-22T10:30:00Z',
    duration: 145,
  },
  {
    id: 'run-2',
    source: 'Indeed Jobs API',
    status: 'success',
    jobsScraped: 892,
    successRate: 96.2,
    errors: 34,
    timestamp: '2024-03-22T09:15:00Z',
    duration: 98,
  },
  {
    id: 'run-3',
    source: 'Greenhouse API',
    status: 'partial',
    jobsScraped: 234,
    successRate: 78.3,
    errors: 65,
    timestamp: '2024-03-22T08:45:00Z',
    duration: 52,
  },
  {
    id: 'run-4',
    source: 'Custom Scraper (TechCorp)',
    status: 'failed',
    jobsScraped: 0,
    successRate: 0,
    errors: 12,
    timestamp: '2024-03-22T07:30:00Z',
    duration: 8,
  },
  {
    id: 'run-5',
    source: 'Lever API',
    status: 'success',
    jobsScraped: 567,
    successRate: 99.1,
    errors: 5,
    timestamp: '2024-03-21T23:00:00Z',
    duration: 76,
  },
];

export const getJobById = (id: string): Job | undefined => {
  return mockJobs.find(job => job.id === id);
};

export const getTasksByJobId = (jobId: string): Task[] => {
  return mockTasks.filter(task => task.jobId === jobId);
};

export const getAutomationBreakdown = (jobId: string): AutomationBreakdown => {
  const job = getJobById(jobId);
  if (!job) {
    return { automatable: 0, humanRequired: 100, complexity: 'medium' };
  }

  return {
    automatable: job.automationPercentage,
    humanRequired: 100 - job.automationPercentage,
    complexity: job.automationPercentage > 80 ? 'low' : job.automationPercentage > 60 ? 'medium' : 'high',
  };
};

export const getAIBlueprint = (jobId: string): AIBlueprint => {
  const job = getJobById(jobId);

  if (job?.title.includes('Support')) {
    return {
      agentType: 'Customer Support AI Agent',
      systemsRequired: ['CRM Integration', 'Knowledge Base', 'Ticketing System', 'NLP Engine'],
      humanInLoopPoints: ['Complex technical issues', 'Escalated complaints', 'Policy exceptions'],
      implementationComplexity: 'medium',
    };
  }

  if (job?.title.includes('SDR') || job?.title.includes('Sales')) {
    return {
      agentType: 'Sales Outreach AI Agent',
      systemsRequired: ['CRM Integration', 'Email Platform', 'Lead Database', 'Personalization Engine'],
      humanInLoopPoints: ['Discovery calls', 'Negotiations', 'Account planning'],
      implementationComplexity: 'medium',
    };
  }

  if (job?.title.includes('Operations') || job?.title.includes('Analyst')) {
    return {
      agentType: 'Data Analysis & Reporting Agent',
      systemsRequired: ['Data Warehouse', 'BI Tools', 'Workflow Automation', 'Report Generator'],
      humanInLoopPoints: ['Strategic decisions', 'Anomaly investigation', 'Stakeholder communication'],
      implementationComplexity: 'low',
    };
  }

  return {
    agentType: 'Automation Agent',
    systemsRequired: ['API Integration', 'Workflow Engine', 'Data Processing'],
    humanInLoopPoints: ['Quality assurance', 'Exception handling', 'Strategic oversight'],
    implementationComplexity: 'medium',
  };
};

export const industryAutomationData = [
  { industry: 'Technology', automation: 76, jobs: 145 },
  { industry: 'Finance', automation: 84, jobs: 89 },
  { industry: 'Healthcare', automation: 68, jobs: 112 },
  { industry: 'Retail', automation: 72, jobs: 78 },
  { industry: 'Media', automation: 81, jobs: 94 },
  { industry: 'Manufacturing', automation: 79, jobs: 56 },
];
